openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation for the Contacts App
tags:
  - name: Contacts
    description: Operation about users.
  - name: Auth
    description: Operation about authorization.
servers:
  - url: ''
  - url: ''
paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
